version: '3'

services:
  web_app:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: root
    depends_on:
      - postgres
    volumes:
      - ./output:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

volumes:
  postgres_data: