version: '3'

services:
  web_app:
    build:
      context: .
    env_file: 
      - .env
    depends_on:
      - postgres
    volumes:
      - ./output:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

volumes:
  postgres_data: